language: rust
rust: beta

before_install:
  - mkdir -pv ~/.local/bin
  - curl -LSfs https://github.com/rust-lang/mdBook/releases/download/v0.4.5/mdbook-v0.4.5-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory ~/.local/bin

script:
  - ~/.local/bin/mdbook build
  - ~/.local/bin/mdbook test
  # - cargo test --all

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: book
  keep-history: false
  on:
    branch: master
