[book]
#  This book is called
title = "用 Rust 写命令行应用"
# ...but friends call it "Clair"
authors = ["The Rust CLI Working Group"]
multilingual = false
translator = "1024chen"
language = "zh-CN"
src = "src"

[output.html]
curly-quotes = true
additional-css = ["src/special-content.css"]
git-repository-url = "https://github.com/1024chen/Command-Line-Applications-in-Rust-cn"
#原书地址： git-repository-url = "https://github.com/rust-cli/book"
site-url = "/book/"

# Linkcheck doesn't find images/SVG so it's not enabled for now
# [output.linkcheck]
