[package]
name = "CLAiR-testing"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
